language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly

matrix:
    allow_failures:
        - php: nightly

before_script:
    - composer install --prefer-dist
    - phpunit --version

script: phpunit
