language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly

matrix:
    allow_failures:
        - php: nightly

before_script:
    # mongo extension is not available on PHP 7
    # this is a workaround till doctrine/mongodb-odm move to mongodb extension
    - composer remove --dev --no-update doctrine/mongodb-odm;
    - composer install --prefer-dist
    - phpunit --version

script: phpunit
